ajustando gcp-landing-zone

diff --git a/gcp-landing-zone.yaml b/gcp-landing-zone.yaml
--- a/gcp-landing-zone.yaml
+++ b/gcp-landing-zone.yaml
@@ -102,6 +102,41 @@ jobs:
               --project="${{ parameters.projectName }}"
 
       - task: Bash@3
+        displayName: "Habilitar BigQuery API"
+        inputs:
+          targetType: inline
+          script: |
+            gcloud services enable bigquery.googleapis.com \
+              --project="${{ parameters.projectName }}"
+
+      - ${{ if endsWith(parameters.projectName, '-prd') }}:
+          - task: Bash@3
+            displayName: "Definir CMEK default no BigQuery (PRD)"
+            inputs:
+              targetType: inline
+              script: |
+                if ! command -v bq &> /dev/null; then
+                  echo "##vso[task.logissue type=error]bq não encontrado na VM do agente (deveria vir junto com o Cloud SDK/gcloud)."
+                  exit 1
+                fi
+
+                bq query --use_legacy_sql=false \
+                  "ALTER PROJECT \`${{ parameters.projectName }}\` SET OPTIONS (\`region-southamerica-east1.default_kms_key_name\`='......')"
+      - ${{ else }}:
+          - task: Bash@3
+            displayName: "Definir CMEK default no BigQuery (NPRD)"
+            inputs:
+              targetType: inline
+              script: |
+                if ! command -v bq &> /dev/null; then
+                  echo "##vso[task.logissue type=error]bq não encontrado na VM do agente (deveria vir junto com o Cloud SDK/gcloud)."
+                  exit 1
+                fi
+
+                bq query --use_legacy_sql=false \
+                  "ALTER PROJECT \`${{ parameters.projectName }}\` SET OPTIONS (\`region-southamerica-east1.default_kms_key_name\`='......')"
+
+      - task: Bash@3
         displayName: "Resumo"
         inputs:
           targetType: inline
